# skelo.yaml — proof of concept: one block

name: skelo-demo

providers:
  - name: local
    type: ollama
    url: http://localhost:11434

agents:
  coder:
    role: worker
    capabilities: [coding]
    provider: local
    model: openai-codex/gpt-5.3-codex
    max_concurrent: 1

  reviewer:
    role: reviewer
    capabilities: [coding]
    provider: local
    model: openai-codex/gpt-5.3-codex
    max_concurrent: 1

pipelines:
  coding:
    stages:
      - name: PENDING
        transitions: [IN_PROGRESS]
      - name: IN_PROGRESS
        route: { role: worker, capability: coding }
        transitions: [REVIEW, BLOCKED]
      - name: REVIEW
        route: { role: reviewer, capability: coding }
        transitions: [DONE, IN_PROGRESS]
      - name: DONE
      - name: BLOCKED
        transitions: [PENDING]

gates:
  - name: needs-assignee
    on: { from: PENDING, to: IN_PROGRESS }
    check: { type: not_empty, field: assigned }
    error: "Assign an agent before starting work"

  - name: structured-feedback
    on: { from: REVIEW, to: IN_PROGRESS }
    check: { type: contains, field: notes, values: ["WHAT:", "WHERE:", "FIX:"] }
    error: "Bounce requires WHAT, WHERE, and FIX in notes"

  - name: done-evidence
    on: { to: DONE }
    check: { type: min_length, field: notes, min: 10 }
    error: "Provide evidence of completion in notes (min 10 chars)"

  - name: max-bounces
    on: { to: IN_PROGRESS }
    check: { type: max_value, field: bounce_count, max: 3 }
    error: "Task exceeded max bounce limit — blocked for review"

storage: sqlite

dashboard:
  enabled: true
  port: 4040
