# skelo.yaml — demo configuration
# Agents cover all roles used by example pipelines.

name: skelo-demo

providers:
  - name: local
    type: ollama
    url: http://localhost:11434

  # Uncomment to use OpenAI-compatible API (OpenRouter, etc.)
  # - name: cloud
  #   type: openai
  #   url: https://openrouter.ai/api/v1
  #   env: OPENROUTER_API_KEY

agents:
  planner:
    role: manager
    capabilities: [planning, writing]
    provider: local
    model: llama3:8b
    max_concurrent: 1

  coder:
    role: worker
    capabilities: [coding, writing, general]
    provider: local
    model: codellama:13b
    max_concurrent: 1

  reviewer:
    role: reviewer
    capabilities: [coding, writing, qa]
    provider: local
    model: llama3:8b
    max_concurrent: 1

  # Uncomment when you have an image provider
  # image-gen:
  #   role: specialist
  #   capabilities: [images]
  #   provider: cloud
  #   model: dall-e-3
  #   max_concurrent: 1

# Legacy pipeline config (required by SkeloConfig type, will be deprecated)
pipelines:
  default:
    stages:
      - name: PENDING
        transitions: [IN_PROGRESS]
      - name: IN_PROGRESS
        route: { role: worker }
        transitions: [DONE]
      - name: DONE

gates: []

storage: sqlite

dashboard:
  enabled: true
  port: 4040
